micronaut:
  application:
    name: complete
  http:
    services:
      default-ms:
        urls:
          - https://jsonplaceholder.typicode.com
        read-timeout: 2000ms
        connect-timeout: 5000ms
        pool:
          enabled: true
          max-connections: 200
